version: '3'
services:
  web:
    build: .
    volumes:
      - ./img-train:/opt/ml/input/data/train
      - ./network.json:/opt/ml/model/network.json
      - .:/data
    ports:
      - 8080:8080
    command: serve
